language: python
# command to install dependencies
install: "pip install -r requirements.txt"
env: STEERCLEAR_SETTINGS=settings/unix_settings.py

# commands to run before scipts. setup testing db
before_script:
- mysql -u root < /scripts/setup_db.sql

# command to run tests
script: nosetests
